enabled: true

handlers:
  - com.xlongwei.light4j.handler.ServiceHandler@service
  - com.xlongwei.light4j.handler.UploadHandler@upload
  - com.xlongwei.light4j.handler.WeixinHandler@weixin
  - com.xlongwei.light4j.provider.WebSocketHandlerProvider@websocket

paths:
  - path: '/service/*'
    method: 'GET'
    exec:
      - service
  - path: '/service/*'
    method: 'POST'
    exec:
      - service
  - path: '/upload/*'
    method: 'POST'
    exec:
      - upload
  - path: '/callback/weixin.xml'
    method: 'GET'
    exec:
      - weixin
  - path: '/callback/weixin.xml'
    method: 'POST'
    exec:
      - weixin
  - path: '/ws/*'
    method: 'GET'
    exec:
      - websocket
