light4j:
  # http://t.xlongwei.com/softwares/library/
  directory: /soft/softwares/library/
  frontUrl: http://cms.xlongwei.com

redis:
  # host:port:db:password:timeout
  configDb: 127.0.0.1:6379:1
  # host:port:dbs:password:timeout:weight
  cacheDbs: 127.0.0.1:6379:3-7

soffice:
  hosts: 127.0.0.1:8100-8102:false

upload:
  save: /soft/uploads/
  url: http://s.xlongwei.com/uploads/