mysql:
  jdbcUrl: jdbc:mysql://localhost:3306/ite?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
  username: ite
  password: 
  minimumIdle: 1
  maximumPoolSize: 10
  autoCommit: true
  connectionTestQuery: SELECT 1
  parameters: 
    cachePrepStmts: true
    prepStmtCacheSize: 100
    cacheResultSetMetadata: true