# Singleton service factory configuration/IoC injection
singletons:
# - com.networknt.server.StartupHookProvider:
  # If you are using mask module to remove sensitive info before logging, uncomment the following line.
  # - com.networknt.server.JsonPathStartupHookProvider
# - com.networknt.server.ShutdownHookProvider:
  # - com.networknt.server.Test1ShutdownHook
- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
#      DriverClassName: com.mysql.jdbc.Driver
#      jdbcUrl: jdbc:mysql://localhost:3306/apijson?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      driverClassName: net.sf.log4jdbc.DriverSpy
      jdbcUrl: jdbc:log4jdbc:mysql://localhost:3306/apijson?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: apijson
      password: apijson
      minimumIdle: 2
      maximumPoolSize: 6
      autoCommit: true
      useServerPrepStmts: true
      cachePrepStmts: true
      cacheCallableStmts: true
      cacheResultSetMetadata: true
      prepStmtCacheSize: 10
      prepStmtCacheSqlLimit: 2048
      connectionTestQuery: SELECT 1
      connectionTimeout: 3000

# redis-manager or memory session
- io.undertow.server.session.SessionConfig:
  - io.undertow.server.session.SessionCookieConfig
#- io.undertow.server.session.SessionManager:
#  - io.undertow.server.session.InMemorySessionManager:
#    - java.lang.String: INMEMORY-SESSION
- com.networknt.session.SessionRepository:
  - com.networknt.session.redis.RedisSessionRepository
- com.networknt.session.SessionManager:
  - com.networknt.session.redis.RedisSessionManager

#- com.networknt.registry.URL:
#  - com.networknt.registry.URLImpl:
#      protocol: light
#      host: localhost
#      port: 8080
#      path: consul
#      parameters:
#        registryRetryPeriod: '30000'
#- com.networknt.consul.client.ConsulClient:
#  - com.networknt.consul.client.ConsulClientImpl:
#    - java.lang.String: http
#    - java.lang.String: consul
#    - int: 8500
#- com.networknt.registry.Registry:
#  - com.networknt.consul.ConsulRegistry
#- com.networknt.balance.LoadBalance:
#  - com.networknt.balance.RoundRobinLoadBalance
#- com.networknt.cluster.Cluster:
#  - com.networknt.cluster.LightCluster
