ip: 0.0.0.0
httpPort: 8080
enableHttp: true
enableHttp2: true
httpsPort: 8443
enableHttps: ${enableHttps:false}
keystoreName: server.keystore
serviceId: com.xlongwei.light4j
enableRegistry: ${enableRegistry:false}
dynamicPort: ${dynamicPort:false}
minPort: 12400
maxPort: 12500